{
    "volumes": {
        "root-gradle-1": null,
        "project-gradle-1": null,
        "project-build-1": null,
        "root-gradle-2": null,
        "project-gradle-2": null,
        "project-build-2": null
    },
    "services": {
        "oru-1": {
            "container_name": "c1",
            "build": ".",
            "ports": [
                "5901:5900"
            ],
            "volumes": [
                "./:/coordination_oru/",
                "project-gradle-1:/coordination_oru/.gradle/",
                "project-build-1:/coordination_oru/build/",
                "root-gradle-1:/root/.gradle/"
            ],
            "environment": {
                "I_CONTAINER": "1"
            },
            "command": "container/index.sh",
            "network_mode": "bridge",
            "shm_size": "4gb"
        },
        "oru-2": {
            "container_name": "c2",
            "build": ".",
            "ports": [
                "5902:5900"
            ],
            "volumes": [
                "./:/coordination_oru/",
                "project-gradle-2:/coordination_oru/.gradle/",
                "project-build-2:/coordination_oru/build/",
                "root-gradle-2:/root/.gradle/"
            ],
            "environment": {
                "I_CONTAINER": "2"
            },
            "command": "container/index.sh",
            "network_mode": "bridge",
            "shm_size": "4gb"
        }
    }
}