volumes:
  root-gradle:
  project-gradle:
  project-build:

services:
  coordination_oru:
    build: .
    ports:
      - "5900:5900"
    volumes:
      - ./:/coordination_oru/
      - project-gradle:/coordination_oru/.gradle/
      - project-build:/coordination_oru/build/
      - root-gradle:/root/.gradle/
    command: container/index.sh
    shm_size: '4gb'  # for Chromium
    network_mode: bridge