volumes:
  gradle:
  project-gradle:
  project-build:

services:
  coordination_oru:
    build: .
    volumes:
      - ./:/coordination_oru/
      - project-gradle:/coordination_oru/.gradle/
      - project-build:/coordination_oru/build/
      - gradle:/root/.gradle/
    working_dir: /coordination_oru/
    command: ./gradlew run -Passert -Pdemo=GeneratedMapTest